import { Inter, Laila, Rubik } from "next/font/google";
import "../styles/_global.scss";
import Header from "./components/header/Header";

export const pageName = "";

const inter = Inter({ subsets: ["latin"] });
const laila = Laila({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});
const rubik = Rubik({ subsets: ["latin"] });

export const metadata = {
  title: {
    default: "Bonema Engineering",
    template: "%s | Bonema Engineering",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children, id }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${laila.className} ${rubik.className} `}
      >
        <main id={id}>
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}
